In [14]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [15]:
net = simpleNet()
print(net.W)

x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)
print(np.argmax(p))

t = np.array([0, 0, 1])
print(net.loss(x, t))

[[ 0.82486181 -0.29033425  0.72936578]
 [ 1.88026777 -1.38463115 -2.63386239]]
[ 2.18715808 -1.42036859 -1.93285669]
0
4.16245759731606


In [9]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.07587232  0.20152275 -0.27739508]
 [ 0.11380849  0.30228413 -0.41609262]]


In [16]:
# 새로운 함수를 정의할 때 간단할 경우 람다 사용하면 편리.

f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)